// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDAcPpYO8dKtUH0zL4yLEqpxC4aaHkHM',
    appId: '1:823488928648:web:b6bff00ebea75097e1383d',
    messagingSenderId: '823488928648',
    projectId: 'khang-project-724d7',
    authDomain: 'khang-project-724d7.firebaseapp.com',
    storageBucket: 'khang-project-724d7.appspot.com',
    measurementId: 'G-E429JYHRWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfz278c5iMTKQAH4AKs0cL53ccDLgPhmo',
    appId: '1:823488928648:android:de58e01085a8e5dfe1383d',
    messagingSenderId: '823488928648',
    projectId: 'khang-project-724d7',
    storageBucket: 'khang-project-724d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE9mISgw7LY8WGJ7sDJliVLXMcMNgU0Ck',
    appId: '1:823488928648:ios:4e3b193a8ad63a07e1383d',
    messagingSenderId: '823488928648',
    projectId: 'khang-project-724d7',
    storageBucket: 'khang-project-724d7.appspot.com',
    iosBundleId: 'com.example.appShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE9mISgw7LY8WGJ7sDJliVLXMcMNgU0Ck',
    appId: '1:823488928648:ios:5eb3eac8bea90d9ae1383d',
    messagingSenderId: '823488928648',
    projectId: 'khang-project-724d7',
    storageBucket: 'khang-project-724d7.appspot.com',
    iosBundleId: 'com.example.appShopping.RunnerTests',
  );
}
